INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

INSERT INTO clientes (nombre, apellido,create_at, email ) VALUES ('Jorge','Rangel','2021-01-01','Jorgeandresr2001-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Ricargo','paz','2021-01-01','Ricargo-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Santiago','Torres','2021-01-01','Santiago-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Kevin','Mauro','2021-01-01','Kevin-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Steve','Jobs','2021-01-01','Steve-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Lina','Ariza','2021-01-01','Lina-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Patico','Guzman','2021-01-01','Patico-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Elenena','Martinez','2021-01-01','Elenena-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('Luzma','Rafaela','2021-01-01','Luzma-20@hotmail.com');
INSERT INTO clientes (nombre, apellido,create_at, email) VALUES ('GordoNuel','Noel','2021-01-01','GordoNuel-20@hotmail.com');

