ALTER TABLE  public.DETALLE_AGENDA ADD CONSTRAINT DETALLE_A_FK1 FOREIGN KEY (COD_HORARIO)
	  REFERENCES  public.HORARIO (COD_HORARIO) ;

ALTER TABLE  public.DETALLE_AGENDA ADD CONSTRAINT DETALLE_A_FK2 FOREIGN KEY (COD_AGENDA)
	  REFERENCES   public.AGENDA (COD_AGENDA) ;

ALTER TABLE  public.DETALLE_ESPECIALIDAD ADD CONSTRAINT DETALLE_FK1 FOREIGN KEY (COD_ESPECIALIDAD)
	  REFERENCES  public.ESPECIALIDAD (COD_ESPECIALIDAD) ;

ALTER TABLE  public.DETALLE_ESPECIALIDAD ADD CONSTRAINT DETALLE_FK2 FOREIGN KEY (COD_MEDICO)
	  REFERENCES  public.MEDICO (COD_MEDICO) ;

ALTER TABLE  public.AGENDA_MEDICO ADD CONSTRAINT AGENDA_M_FK1 FOREIGN KEY (COD_MEDICO)
	  REFERENCES  public.MEDICO (COD_MEDICO);

ALTER TABLE  public.AGENDA_MEDICO ADD CONSTRAINT AGENDA_M_FK2 FOREIGN KEY (COD_AGENDA)
	  REFERENCES  public.AGENDA (COD_AGENDA) ;

ALTER TABLE  public.MEDICO ADD CONSTRAINT MEDICO_FK1 FOREIGN KEY (COD_USUARIO)
	  REFERENCES  public.USUARIO (COD_USUARIO);

ALTER TABLE  public.MEDICO ADD CONSTRAINT MEDICO_FK2 FOREIGN KEY (COD_CONSULTORIO)
	  REFERENCES  public.CONSULTORIO (COD_CONSULTORIO);
