CREATE TABLE  public.HORARIO
   (	COD_HORARIO INT NOT NULL,
	HORA_INICIO DATE,
	HORA_FIN DATE,
	 CONSTRAINT HORARIO_DISPO_PK PRIMARY KEY (COD_HORARIO)
   );


CREATE TABLE  public.AGENDA
   (	COD_AGENDA INT NOT NULL,
	FECHA_AGENDA DATE,
	 CONSTRAINT AGENDA_PK PRIMARY KEY (COD_AGENDA)
   );


CREATE TABLE public.DETALLE_AGENDA
    (   COD_HORARIO INT NOT NULL,
        COD_AGENDA INT NOT NULL,
         CONSTRAINT DETALLE_AG_PK PRIMARY KEY (COD_HORARIO, COD_AGENDA)
    );


CREATE TABLE  public.AGENDA_MEDICO
   (	COD_MEDICO INT NOT NULL,
	COD_AGENDA INT NOT NULL,
	 CONSTRAINT AGENDA_MEDICO_PK PRIMARY KEY (COD_MEDICO, COD_AGENDA)
   );


CREATE TABLE  public.MEDICO
 (	COD_MEDICO INT NOT NULL,
	COD_USUARIO INT NOT NULL,
	COD_CONSULTORIO INT NOT NULL,
	 CONSTRAINT MEDICO_PK PRIMARY KEY (COD_MEDICO)
   );


CREATE TABLE  public.USUARIO
   (	COD_USUARIO INT NOT NULL,
        NOM_USUARIO VARCHAR(45) NULL,
        APELLIDO_USUARIO VARCHAR(45) NULL,
        ALIAS_USUARIO VARCHAR(45) NULL,
        CLAVE_USUARIO VARCHAR(45) NULL,
	 CONSTRAINT USUARIO_PK PRIMARY KEY (COD_USUARIO)
   );


CREATE TABLE  public.CONSULTORIO
   (	COD_CONSULTORIO INT NOT NULL,
	NOM_CONSULTORIO VARCHAR(100) NULL,
	 CONSTRAINT CONSULTORIO_PK PRIMARY KEY (COD_CONSULTORIO)
   );


CREATE TABLE  public.ESPECIALIDAD
   (	COD_ESPECIALIDAD INT NOT NULL,
        NOM_ESPECIALIDAD VARCHAR(45) NULL,
	 CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (COD_ESPECIALIDAD)
   );


CREATE TABLE public.DETALLE_ESPECIALIDAD
   (   COD_ESPECIALIDAD INT NOT NULL,
       COD_MEDICO INT NOT NULL,
        CONSTRAINT DETALLE_PK PRIMARY KEY (COD_MEDICO)
   );